### ISSUE TITLE
Bitcoin tumbler

### ISSUE THREAD

**Issue by jamdz** [blackout314/blackout314.github.io#1]
Hello do you have any tumbler script working and available

**Comment by blackout314** [comment]
what do you mean with tumbler script?

**Comment by jamdz** [comment]
Bitcoin tumbler website script do you have any functioning and for sale.

**Comment by blackout314** [comment]
i can made always, but i dont understand what functionality you want.

**Comment by jamdz** [comment]
What functionality do you think is best
